// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: images_service.proto

package image

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImagesServiceError_ErrorCode int32

const (
	ImagesServiceError_UNSPECIFIED_ERROR  ImagesServiceError_ErrorCode = 1
	ImagesServiceError_BAD_TRANSFORM_DATA ImagesServiceError_ErrorCode = 2
	ImagesServiceError_NOT_IMAGE          ImagesServiceError_ErrorCode = 3
	ImagesServiceError_BAD_IMAGE_DATA     ImagesServiceError_ErrorCode = 4
	ImagesServiceError_IMAGE_TOO_LARGE    ImagesServiceError_ErrorCode = 5
	ImagesServiceError_INVALID_BLOB_KEY   ImagesServiceError_ErrorCode = 6
	ImagesServiceError_ACCESS_DENIED      ImagesServiceError_ErrorCode = 7
	ImagesServiceError_OBJECT_NOT_FOUND   ImagesServiceError_ErrorCode = 8
)

// Enum value maps for ImagesServiceError_ErrorCode.
var (
	ImagesServiceError_ErrorCode_name = map[int32]string{
		1: "UNSPECIFIED_ERROR",
		2: "BAD_TRANSFORM_DATA",
		3: "NOT_IMAGE",
		4: "BAD_IMAGE_DATA",
		5: "IMAGE_TOO_LARGE",
		6: "INVALID_BLOB_KEY",
		7: "ACCESS_DENIED",
		8: "OBJECT_NOT_FOUND",
	}
	ImagesServiceError_ErrorCode_value = map[string]int32{
		"UNSPECIFIED_ERROR":  1,
		"BAD_TRANSFORM_DATA": 2,
		"NOT_IMAGE":          3,
		"BAD_IMAGE_DATA":     4,
		"IMAGE_TOO_LARGE":    5,
		"INVALID_BLOB_KEY":   6,
		"ACCESS_DENIED":      7,
		"OBJECT_NOT_FOUND":   8,
	}
)

func (x ImagesServiceError_ErrorCode) Enum() *ImagesServiceError_ErrorCode {
	p := new(ImagesServiceError_ErrorCode)
	*p = x
	return p
}

func (x ImagesServiceError_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImagesServiceError_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_images_service_proto_enumTypes[0].Descriptor()
}

func (ImagesServiceError_ErrorCode) Type() protoreflect.EnumType {
	return &file_images_service_proto_enumTypes[0]
}

func (x ImagesServiceError_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ImagesServiceError_ErrorCode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ImagesServiceError_ErrorCode(num)
	return nil
}

// Deprecated: Use ImagesServiceError_ErrorCode.Descriptor instead.
func (ImagesServiceError_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{0, 0}
}

type ImagesServiceTransform_Type int32

const (
	ImagesServiceTransform_RESIZE           ImagesServiceTransform_Type = 1
	ImagesServiceTransform_ROTATE           ImagesServiceTransform_Type = 2
	ImagesServiceTransform_HORIZONTAL_FLIP  ImagesServiceTransform_Type = 3
	ImagesServiceTransform_VERTICAL_FLIP    ImagesServiceTransform_Type = 4
	ImagesServiceTransform_CROP             ImagesServiceTransform_Type = 5
	ImagesServiceTransform_IM_FEELING_LUCKY ImagesServiceTransform_Type = 6
)

// Enum value maps for ImagesServiceTransform_Type.
var (
	ImagesServiceTransform_Type_name = map[int32]string{
		1: "RESIZE",
		2: "ROTATE",
		3: "HORIZONTAL_FLIP",
		4: "VERTICAL_FLIP",
		5: "CROP",
		6: "IM_FEELING_LUCKY",
	}
	ImagesServiceTransform_Type_value = map[string]int32{
		"RESIZE":           1,
		"ROTATE":           2,
		"HORIZONTAL_FLIP":  3,
		"VERTICAL_FLIP":    4,
		"CROP":             5,
		"IM_FEELING_LUCKY": 6,
	}
)

func (x ImagesServiceTransform_Type) Enum() *ImagesServiceTransform_Type {
	p := new(ImagesServiceTransform_Type)
	*p = x
	return p
}

func (x ImagesServiceTransform_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImagesServiceTransform_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_images_service_proto_enumTypes[1].Descriptor()
}

func (ImagesServiceTransform_Type) Type() protoreflect.EnumType {
	return &file_images_service_proto_enumTypes[1]
}

func (x ImagesServiceTransform_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ImagesServiceTransform_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ImagesServiceTransform_Type(num)
	return nil
}

// Deprecated: Use ImagesServiceTransform_Type.Descriptor instead.
func (ImagesServiceTransform_Type) EnumDescriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{1, 0}
}

type InputSettings_ORIENTATION_CORRECTION_TYPE int32

const (
	InputSettings_UNCHANGED_ORIENTATION InputSettings_ORIENTATION_CORRECTION_TYPE = 0
	InputSettings_CORRECT_ORIENTATION   InputSettings_ORIENTATION_CORRECTION_TYPE = 1
)

// Enum value maps for InputSettings_ORIENTATION_CORRECTION_TYPE.
var (
	InputSettings_ORIENTATION_CORRECTION_TYPE_name = map[int32]string{
		0: "UNCHANGED_ORIENTATION",
		1: "CORRECT_ORIENTATION",
	}
	InputSettings_ORIENTATION_CORRECTION_TYPE_value = map[string]int32{
		"UNCHANGED_ORIENTATION": 0,
		"CORRECT_ORIENTATION":   1,
	}
)

func (x InputSettings_ORIENTATION_CORRECTION_TYPE) Enum() *InputSettings_ORIENTATION_CORRECTION_TYPE {
	p := new(InputSettings_ORIENTATION_CORRECTION_TYPE)
	*p = x
	return p
}

func (x InputSettings_ORIENTATION_CORRECTION_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InputSettings_ORIENTATION_CORRECTION_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_images_service_proto_enumTypes[2].Descriptor()
}

func (InputSettings_ORIENTATION_CORRECTION_TYPE) Type() protoreflect.EnumType {
	return &file_images_service_proto_enumTypes[2]
}

func (x InputSettings_ORIENTATION_CORRECTION_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *InputSettings_ORIENTATION_CORRECTION_TYPE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = InputSettings_ORIENTATION_CORRECTION_TYPE(num)
	return nil
}

// Deprecated: Use InputSettings_ORIENTATION_CORRECTION_TYPE.Descriptor instead.
func (InputSettings_ORIENTATION_CORRECTION_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{4, 0}
}

type OutputSettings_MIME_TYPE int32

const (
	OutputSettings_PNG  OutputSettings_MIME_TYPE = 0
	OutputSettings_JPEG OutputSettings_MIME_TYPE = 1
	OutputSettings_WEBP OutputSettings_MIME_TYPE = 2
)

// Enum value maps for OutputSettings_MIME_TYPE.
var (
	OutputSettings_MIME_TYPE_name = map[int32]string{
		0: "PNG",
		1: "JPEG",
		2: "WEBP",
	}
	OutputSettings_MIME_TYPE_value = map[string]int32{
		"PNG":  0,
		"JPEG": 1,
		"WEBP": 2,
	}
)

func (x OutputSettings_MIME_TYPE) Enum() *OutputSettings_MIME_TYPE {
	p := new(OutputSettings_MIME_TYPE)
	*p = x
	return p
}

func (x OutputSettings_MIME_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputSettings_MIME_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_images_service_proto_enumTypes[3].Descriptor()
}

func (OutputSettings_MIME_TYPE) Type() protoreflect.EnumType {
	return &file_images_service_proto_enumTypes[3]
}

func (x OutputSettings_MIME_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *OutputSettings_MIME_TYPE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = OutputSettings_MIME_TYPE(num)
	return nil
}

// Deprecated: Use OutputSettings_MIME_TYPE.Descriptor instead.
func (OutputSettings_MIME_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{5, 0}
}

type CompositeImageOptions_ANCHOR int32

const (
	CompositeImageOptions_TOP_LEFT     CompositeImageOptions_ANCHOR = 0
	CompositeImageOptions_TOP          CompositeImageOptions_ANCHOR = 1
	CompositeImageOptions_TOP_RIGHT    CompositeImageOptions_ANCHOR = 2
	CompositeImageOptions_LEFT         CompositeImageOptions_ANCHOR = 3
	CompositeImageOptions_CENTER       CompositeImageOptions_ANCHOR = 4
	CompositeImageOptions_RIGHT        CompositeImageOptions_ANCHOR = 5
	CompositeImageOptions_BOTTOM_LEFT  CompositeImageOptions_ANCHOR = 6
	CompositeImageOptions_BOTTOM       CompositeImageOptions_ANCHOR = 7
	CompositeImageOptions_BOTTOM_RIGHT CompositeImageOptions_ANCHOR = 8
)

// Enum value maps for CompositeImageOptions_ANCHOR.
var (
	CompositeImageOptions_ANCHOR_name = map[int32]string{
		0: "TOP_LEFT",
		1: "TOP",
		2: "TOP_RIGHT",
		3: "LEFT",
		4: "CENTER",
		5: "RIGHT",
		6: "BOTTOM_LEFT",
		7: "BOTTOM",
		8: "BOTTOM_RIGHT",
	}
	CompositeImageOptions_ANCHOR_value = map[string]int32{
		"TOP_LEFT":     0,
		"TOP":          1,
		"TOP_RIGHT":    2,
		"LEFT":         3,
		"CENTER":       4,
		"RIGHT":        5,
		"BOTTOM_LEFT":  6,
		"BOTTOM":       7,
		"BOTTOM_RIGHT": 8,
	}
)

func (x CompositeImageOptions_ANCHOR) Enum() *CompositeImageOptions_ANCHOR {
	p := new(CompositeImageOptions_ANCHOR)
	*p = x
	return p
}

func (x CompositeImageOptions_ANCHOR) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompositeImageOptions_ANCHOR) Descriptor() protoreflect.EnumDescriptor {
	return file_images_service_proto_enumTypes[4].Descriptor()
}

func (CompositeImageOptions_ANCHOR) Type() protoreflect.EnumType {
	return &file_images_service_proto_enumTypes[4]
}

func (x CompositeImageOptions_ANCHOR) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CompositeImageOptions_ANCHOR) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CompositeImageOptions_ANCHOR(num)
	return nil
}

// Deprecated: Use CompositeImageOptions_ANCHOR.Descriptor instead.
func (CompositeImageOptions_ANCHOR) EnumDescriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{8, 0}
}

type ImagesServiceError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ImagesServiceError) Reset() {
	*x = ImagesServiceError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_images_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImagesServiceError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagesServiceError) ProtoMessage() {}

func (x *ImagesServiceError) ProtoReflect() protoreflect.Message {
	mi := &file_images_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagesServiceError.ProtoReflect.Descriptor instead.
func (*ImagesServiceError) Descriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{0}
}

type ImagesServiceTransform struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ImagesServiceTransform) Reset() {
	*x = ImagesServiceTransform{}
	if protoimpl.UnsafeEnabled {
		mi := &file_images_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImagesServiceTransform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagesServiceTransform) ProtoMessage() {}

func (x *ImagesServiceTransform) ProtoReflect() protoreflect.Message {
	mi := &file_images_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagesServiceTransform.ProtoReflect.Descriptor instead.
func (*ImagesServiceTransform) Descriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{1}
}

type Transform struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width          *int32   `protobuf:"varint,1,opt,name=width" json:"width,omitempty"`
	Height         *int32   `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
	CropToFit      *bool    `protobuf:"varint,11,opt,name=crop_to_fit,json=cropToFit,def=0" json:"crop_to_fit,omitempty"`
	CropOffsetX    *float32 `protobuf:"fixed32,12,opt,name=crop_offset_x,json=cropOffsetX,def=0.5" json:"crop_offset_x,omitempty"`
	CropOffsetY    *float32 `protobuf:"fixed32,13,opt,name=crop_offset_y,json=cropOffsetY,def=0.5" json:"crop_offset_y,omitempty"`
	Rotate         *int32   `protobuf:"varint,3,opt,name=rotate,def=0" json:"rotate,omitempty"`
	HorizontalFlip *bool    `protobuf:"varint,4,opt,name=horizontal_flip,json=horizontalFlip,def=0" json:"horizontal_flip,omitempty"`
	VerticalFlip   *bool    `protobuf:"varint,5,opt,name=vertical_flip,json=verticalFlip,def=0" json:"vertical_flip,omitempty"`
	CropLeftX      *float32 `protobuf:"fixed32,6,opt,name=crop_left_x,json=cropLeftX,def=0" json:"crop_left_x,omitempty"`
	CropTopY       *float32 `protobuf:"fixed32,7,opt,name=crop_top_y,json=cropTopY,def=0" json:"crop_top_y,omitempty"`
	CropRightX     *float32 `protobuf:"fixed32,8,opt,name=crop_right_x,json=cropRightX,def=1" json:"crop_right_x,omitempty"`
	CropBottomY    *float32 `protobuf:"fixed32,9,opt,name=crop_bottom_y,json=cropBottomY,def=1" json:"crop_bottom_y,omitempty"`
	Autolevels     *bool    `protobuf:"varint,10,opt,name=autolevels,def=0" json:"autolevels,omitempty"`
	AllowStretch   *bool    `protobuf:"varint,14,opt,name=allow_stretch,json=allowStretch,def=0" json:"allow_stretch,omitempty"`
}

// Default values for Transform fields.
const (
	Default_Transform_CropToFit      = bool(false)
	Default_Transform_CropOffsetX    = float32(0.5)
	Default_Transform_CropOffsetY    = float32(0.5)
	Default_Transform_Rotate         = int32(0)
	Default_Transform_HorizontalFlip = bool(false)
	Default_Transform_VerticalFlip   = bool(false)
	Default_Transform_CropLeftX      = float32(0)
	Default_Transform_CropTopY       = float32(0)
	Default_Transform_CropRightX     = float32(1)
	Default_Transform_CropBottomY    = float32(1)
	Default_Transform_Autolevels     = bool(false)
	Default_Transform_AllowStretch   = bool(false)
)

func (x *Transform) Reset() {
	*x = Transform{}
	if protoimpl.UnsafeEnabled {
		mi := &file_images_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transform) ProtoMessage() {}

func (x *Transform) ProtoReflect() protoreflect.Message {
	mi := &file_images_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transform.ProtoReflect.Descriptor instead.
func (*Transform) Descriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{2}
}

func (x *Transform) GetWidth() int32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *Transform) GetHeight() int32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *Transform) GetCropToFit() bool {
	if x != nil && x.CropToFit != nil {
		return *x.CropToFit
	}
	return Default_Transform_CropToFit
}

func (x *Transform) GetCropOffsetX() float32 {
	if x != nil && x.CropOffsetX != nil {
		return *x.CropOffsetX
	}
	return Default_Transform_CropOffsetX
}

func (x *Transform) GetCropOffsetY() float32 {
	if x != nil && x.CropOffsetY != nil {
		return *x.CropOffsetY
	}
	return Default_Transform_CropOffsetY
}

func (x *Transform) GetRotate() int32 {
	if x != nil && x.Rotate != nil {
		return *x.Rotate
	}
	return Default_Transform_Rotate
}

func (x *Transform) GetHorizontalFlip() bool {
	if x != nil && x.HorizontalFlip != nil {
		return *x.HorizontalFlip
	}
	return Default_Transform_HorizontalFlip
}

func (x *Transform) GetVerticalFlip() bool {
	if x != nil && x.VerticalFlip != nil {
		return *x.VerticalFlip
	}
	return Default_Transform_VerticalFlip
}

func (x *Transform) GetCropLeftX() float32 {
	if x != nil && x.CropLeftX != nil {
		return *x.CropLeftX
	}
	return Default_Transform_CropLeftX
}

func (x *Transform) GetCropTopY() float32 {
	if x != nil && x.CropTopY != nil {
		return *x.CropTopY
	}
	return Default_Transform_CropTopY
}

func (x *Transform) GetCropRightX() float32 {
	if x != nil && x.CropRightX != nil {
		return *x.CropRightX
	}
	return Default_Transform_CropRightX
}

func (x *Transform) GetCropBottomY() float32 {
	if x != nil && x.CropBottomY != nil {
		return *x.CropBottomY
	}
	return Default_Transform_CropBottomY
}

func (x *Transform) GetAutolevels() bool {
	if x != nil && x.Autolevels != nil {
		return *x.Autolevels
	}
	return Default_Transform_Autolevels
}

func (x *Transform) GetAllowStretch() bool {
	if x != nil && x.AllowStretch != nil {
		return *x.AllowStretch
	}
	return Default_Transform_AllowStretch
}

type ImageData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []byte  `protobuf:"bytes,1,req,name=content" json:"content,omitempty"`
	BlobKey *string `protobuf:"bytes,2,opt,name=blob_key,json=blobKey" json:"blob_key,omitempty"`
	Width   *int32  `protobuf:"varint,3,opt,name=width" json:"width,omitempty"`
	Height  *int32  `protobuf:"varint,4,opt,name=height" json:"height,omitempty"`
}

func (x *ImageData) Reset() {
	*x = ImageData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_images_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageData) ProtoMessage() {}

func (x *ImageData) ProtoReflect() protoreflect.Message {
	mi := &file_images_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageData.ProtoReflect.Descriptor instead.
func (*ImageData) Descriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{3}
}

func (x *ImageData) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ImageData) GetBlobKey() string {
	if x != nil && x.BlobKey != nil {
		return *x.BlobKey
	}
	return ""
}

func (x *ImageData) GetWidth() int32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *ImageData) GetHeight() int32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

type InputSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrectExifOrientation     *InputSettings_ORIENTATION_CORRECTION_TYPE `protobuf:"varint,1,opt,name=correct_exif_orientation,json=correctExifOrientation,enum=appengine.v2.InputSettings_ORIENTATION_CORRECTION_TYPE,def=0" json:"correct_exif_orientation,omitempty"`
	ParseMetadata              *bool                                      `protobuf:"varint,2,opt,name=parse_metadata,json=parseMetadata,def=0" json:"parse_metadata,omitempty"`
	TransparentSubstitutionRgb *int32                                     `protobuf:"varint,3,opt,name=transparent_substitution_rgb,json=transparentSubstitutionRgb" json:"transparent_substitution_rgb,omitempty"`
}

// Default values for InputSettings fields.
const (
	Default_InputSettings_CorrectExifOrientation = InputSettings_UNCHANGED_ORIENTATION
	Default_InputSettings_ParseMetadata          = bool(false)
)

func (x *InputSettings) Reset() {
	*x = InputSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_images_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputSettings) ProtoMessage() {}

func (x *InputSettings) ProtoReflect() protoreflect.Message {
	mi := &file_images_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputSettings.ProtoReflect.Descriptor instead.
func (*InputSettings) Descriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{4}
}

func (x *InputSettings) GetCorrectExifOrientation() InputSettings_ORIENTATION_CORRECTION_TYPE {
	if x != nil && x.CorrectExifOrientation != nil {
		return *x.CorrectExifOrientation
	}
	return Default_InputSettings_CorrectExifOrientation
}

func (x *InputSettings) GetParseMetadata() bool {
	if x != nil && x.ParseMetadata != nil {
		return *x.ParseMetadata
	}
	return Default_InputSettings_ParseMetadata
}

func (x *InputSettings) GetTransparentSubstitutionRgb() int32 {
	if x != nil && x.TransparentSubstitutionRgb != nil {
		return *x.TransparentSubstitutionRgb
	}
	return 0
}

type OutputSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MimeType *OutputSettings_MIME_TYPE `protobuf:"varint,1,opt,name=mime_type,json=mimeType,enum=appengine.v2.OutputSettings_MIME_TYPE,def=0" json:"mime_type,omitempty"`
	Quality  *int32                    `protobuf:"varint,2,opt,name=quality" json:"quality,omitempty"`
}

// Default values for OutputSettings fields.
const (
	Default_OutputSettings_MimeType = OutputSettings_PNG
)

func (x *OutputSettings) Reset() {
	*x = OutputSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_images_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutputSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputSettings) ProtoMessage() {}

func (x *OutputSettings) ProtoReflect() protoreflect.Message {
	mi := &file_images_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputSettings.ProtoReflect.Descriptor instead.
func (*OutputSettings) Descriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{5}
}

func (x *OutputSettings) GetMimeType() OutputSettings_MIME_TYPE {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return Default_OutputSettings_MimeType
}

func (x *OutputSettings) GetQuality() int32 {
	if x != nil && x.Quality != nil {
		return *x.Quality
	}
	return 0
}

type ImagesTransformRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image     *ImageData      `protobuf:"bytes,1,req,name=image" json:"image,omitempty"`
	Transform []*Transform    `protobuf:"bytes,2,rep,name=transform" json:"transform,omitempty"`
	Output    *OutputSettings `protobuf:"bytes,3,req,name=output" json:"output,omitempty"`
	Input     *InputSettings  `protobuf:"bytes,4,opt,name=input" json:"input,omitempty"`
}

func (x *ImagesTransformRequest) Reset() {
	*x = ImagesTransformRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_images_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImagesTransformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagesTransformRequest) ProtoMessage() {}

func (x *ImagesTransformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_images_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagesTransformRequest.ProtoReflect.Descriptor instead.
func (*ImagesTransformRequest) Descriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{6}
}

func (x *ImagesTransformRequest) GetImage() *ImageData {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ImagesTransformRequest) GetTransform() []*Transform {
	if x != nil {
		return x.Transform
	}
	return nil
}

func (x *ImagesTransformRequest) GetOutput() *OutputSettings {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ImagesTransformRequest) GetInput() *InputSettings {
	if x != nil {
		return x.Input
	}
	return nil
}

type ImagesTransformResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image          *ImageData `protobuf:"bytes,1,req,name=image" json:"image,omitempty"`
	SourceMetadata *string    `protobuf:"bytes,2,opt,name=source_metadata,json=sourceMetadata" json:"source_metadata,omitempty"`
}

func (x *ImagesTransformResponse) Reset() {
	*x = ImagesTransformResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_images_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImagesTransformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagesTransformResponse) ProtoMessage() {}

func (x *ImagesTransformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_images_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagesTransformResponse.ProtoReflect.Descriptor instead.
func (*ImagesTransformResponse) Descriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{7}
}

func (x *ImagesTransformResponse) GetImage() *ImageData {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ImagesTransformResponse) GetSourceMetadata() string {
	if x != nil && x.SourceMetadata != nil {
		return *x.SourceMetadata
	}
	return ""
}

type CompositeImageOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceIndex *int32                        `protobuf:"varint,1,req,name=source_index,json=sourceIndex" json:"source_index,omitempty"`
	XOffset     *int32                        `protobuf:"varint,2,req,name=x_offset,json=xOffset" json:"x_offset,omitempty"`
	YOffset     *int32                        `protobuf:"varint,3,req,name=y_offset,json=yOffset" json:"y_offset,omitempty"`
	Opacity     *float32                      `protobuf:"fixed32,4,req,name=opacity" json:"opacity,omitempty"`
	Anchor      *CompositeImageOptions_ANCHOR `protobuf:"varint,5,req,name=anchor,enum=appengine.v2.CompositeImageOptions_ANCHOR" json:"anchor,omitempty"`
}

func (x *CompositeImageOptions) Reset() {
	*x = CompositeImageOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_images_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompositeImageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositeImageOptions) ProtoMessage() {}

func (x *CompositeImageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_images_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositeImageOptions.ProtoReflect.Descriptor instead.
func (*CompositeImageOptions) Descriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{8}
}

func (x *CompositeImageOptions) GetSourceIndex() int32 {
	if x != nil && x.SourceIndex != nil {
		return *x.SourceIndex
	}
	return 0
}

func (x *CompositeImageOptions) GetXOffset() int32 {
	if x != nil && x.XOffset != nil {
		return *x.XOffset
	}
	return 0
}

func (x *CompositeImageOptions) GetYOffset() int32 {
	if x != nil && x.YOffset != nil {
		return *x.YOffset
	}
	return 0
}

func (x *CompositeImageOptions) GetOpacity() float32 {
	if x != nil && x.Opacity != nil {
		return *x.Opacity
	}
	return 0
}

func (x *CompositeImageOptions) GetAnchor() CompositeImageOptions_ANCHOR {
	if x != nil && x.Anchor != nil {
		return *x.Anchor
	}
	return CompositeImageOptions_TOP_LEFT
}

type ImagesCanvas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width  *int32          `protobuf:"varint,1,req,name=width" json:"width,omitempty"`
	Height *int32          `protobuf:"varint,2,req,name=height" json:"height,omitempty"`
	Output *OutputSettings `protobuf:"bytes,3,req,name=output" json:"output,omitempty"`
	Color  *int32          `protobuf:"varint,4,opt,name=color,def=-1" json:"color,omitempty"`
}

// Default values for ImagesCanvas fields.
const (
	Default_ImagesCanvas_Color = int32(-1)
)

func (x *ImagesCanvas) Reset() {
	*x = ImagesCanvas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_images_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImagesCanvas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagesCanvas) ProtoMessage() {}

func (x *ImagesCanvas) ProtoReflect() protoreflect.Message {
	mi := &file_images_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagesCanvas.ProtoReflect.Descriptor instead.
func (*ImagesCanvas) Descriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{9}
}

func (x *ImagesCanvas) GetWidth() int32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *ImagesCanvas) GetHeight() int32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *ImagesCanvas) GetOutput() *OutputSettings {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ImagesCanvas) GetColor() int32 {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return Default_ImagesCanvas_Color
}

type ImagesCompositeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image   []*ImageData             `protobuf:"bytes,1,rep,name=image" json:"image,omitempty"`
	Options []*CompositeImageOptions `protobuf:"bytes,2,rep,name=options" json:"options,omitempty"`
	Canvas  *ImagesCanvas            `protobuf:"bytes,3,req,name=canvas" json:"canvas,omitempty"`
}

func (x *ImagesCompositeRequest) Reset() {
	*x = ImagesCompositeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_images_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImagesCompositeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagesCompositeRequest) ProtoMessage() {}

func (x *ImagesCompositeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_images_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagesCompositeRequest.ProtoReflect.Descriptor instead.
func (*ImagesCompositeRequest) Descriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{10}
}

func (x *ImagesCompositeRequest) GetImage() []*ImageData {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ImagesCompositeRequest) GetOptions() []*CompositeImageOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ImagesCompositeRequest) GetCanvas() *ImagesCanvas {
	if x != nil {
		return x.Canvas
	}
	return nil
}

type ImagesCompositeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image *ImageData `protobuf:"bytes,1,req,name=image" json:"image,omitempty"`
}

func (x *ImagesCompositeResponse) Reset() {
	*x = ImagesCompositeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_images_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImagesCompositeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagesCompositeResponse) ProtoMessage() {}

func (x *ImagesCompositeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_images_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagesCompositeResponse.ProtoReflect.Descriptor instead.
func (*ImagesCompositeResponse) Descriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{11}
}

func (x *ImagesCompositeResponse) GetImage() *ImageData {
	if x != nil {
		return x.Image
	}
	return nil
}

type ImagesHistogramRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image *ImageData `protobuf:"bytes,1,req,name=image" json:"image,omitempty"`
}

func (x *ImagesHistogramRequest) Reset() {
	*x = ImagesHistogramRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_images_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImagesHistogramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagesHistogramRequest) ProtoMessage() {}

func (x *ImagesHistogramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_images_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagesHistogramRequest.ProtoReflect.Descriptor instead.
func (*ImagesHistogramRequest) Descriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{12}
}

func (x *ImagesHistogramRequest) GetImage() *ImageData {
	if x != nil {
		return x.Image
	}
	return nil
}

type ImagesHistogram struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Red   []int32 `protobuf:"varint,1,rep,name=red" json:"red,omitempty"`
	Green []int32 `protobuf:"varint,2,rep,name=green" json:"green,omitempty"`
	Blue  []int32 `protobuf:"varint,3,rep,name=blue" json:"blue,omitempty"`
}

func (x *ImagesHistogram) Reset() {
	*x = ImagesHistogram{}
	if protoimpl.UnsafeEnabled {
		mi := &file_images_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImagesHistogram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagesHistogram) ProtoMessage() {}

func (x *ImagesHistogram) ProtoReflect() protoreflect.Message {
	mi := &file_images_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagesHistogram.ProtoReflect.Descriptor instead.
func (*ImagesHistogram) Descriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{13}
}

func (x *ImagesHistogram) GetRed() []int32 {
	if x != nil {
		return x.Red
	}
	return nil
}

func (x *ImagesHistogram) GetGreen() []int32 {
	if x != nil {
		return x.Green
	}
	return nil
}

func (x *ImagesHistogram) GetBlue() []int32 {
	if x != nil {
		return x.Blue
	}
	return nil
}

type ImagesHistogramResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Histogram *ImagesHistogram `protobuf:"bytes,1,req,name=histogram" json:"histogram,omitempty"`
}

func (x *ImagesHistogramResponse) Reset() {
	*x = ImagesHistogramResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_images_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImagesHistogramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagesHistogramResponse) ProtoMessage() {}

func (x *ImagesHistogramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_images_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagesHistogramResponse.ProtoReflect.Descriptor instead.
func (*ImagesHistogramResponse) Descriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{14}
}

func (x *ImagesHistogramResponse) GetHistogram() *ImagesHistogram {
	if x != nil {
		return x.Histogram
	}
	return nil
}

type ImagesGetUrlBaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlobKey         *string `protobuf:"bytes,1,req,name=blob_key,json=blobKey" json:"blob_key,omitempty"`
	CreateSecureUrl *bool   `protobuf:"varint,2,opt,name=create_secure_url,json=createSecureUrl,def=0" json:"create_secure_url,omitempty"`
}

// Default values for ImagesGetUrlBaseRequest fields.
const (
	Default_ImagesGetUrlBaseRequest_CreateSecureUrl = bool(false)
)

func (x *ImagesGetUrlBaseRequest) Reset() {
	*x = ImagesGetUrlBaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_images_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImagesGetUrlBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagesGetUrlBaseRequest) ProtoMessage() {}

func (x *ImagesGetUrlBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_images_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagesGetUrlBaseRequest.ProtoReflect.Descriptor instead.
func (*ImagesGetUrlBaseRequest) Descriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{15}
}

func (x *ImagesGetUrlBaseRequest) GetBlobKey() string {
	if x != nil && x.BlobKey != nil {
		return *x.BlobKey
	}
	return ""
}

func (x *ImagesGetUrlBaseRequest) GetCreateSecureUrl() bool {
	if x != nil && x.CreateSecureUrl != nil {
		return *x.CreateSecureUrl
	}
	return Default_ImagesGetUrlBaseRequest_CreateSecureUrl
}

type ImagesGetUrlBaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url *string `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
}

func (x *ImagesGetUrlBaseResponse) Reset() {
	*x = ImagesGetUrlBaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_images_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImagesGetUrlBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagesGetUrlBaseResponse) ProtoMessage() {}

func (x *ImagesGetUrlBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_images_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagesGetUrlBaseResponse.ProtoReflect.Descriptor instead.
func (*ImagesGetUrlBaseResponse) Descriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{16}
}

func (x *ImagesGetUrlBaseResponse) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

type ImagesDeleteUrlBaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlobKey *string `protobuf:"bytes,1,req,name=blob_key,json=blobKey" json:"blob_key,omitempty"`
}

func (x *ImagesDeleteUrlBaseRequest) Reset() {
	*x = ImagesDeleteUrlBaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_images_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImagesDeleteUrlBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagesDeleteUrlBaseRequest) ProtoMessage() {}

func (x *ImagesDeleteUrlBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_images_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagesDeleteUrlBaseRequest.ProtoReflect.Descriptor instead.
func (*ImagesDeleteUrlBaseRequest) Descriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{17}
}

func (x *ImagesDeleteUrlBaseRequest) GetBlobKey() string {
	if x != nil && x.BlobKey != nil {
		return *x.BlobKey
	}
	return ""
}

type ImagesDeleteUrlBaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ImagesDeleteUrlBaseResponse) Reset() {
	*x = ImagesDeleteUrlBaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_images_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImagesDeleteUrlBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagesDeleteUrlBaseResponse) ProtoMessage() {}

func (x *ImagesDeleteUrlBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_images_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagesDeleteUrlBaseResponse.ProtoReflect.Descriptor instead.
func (*ImagesDeleteUrlBaseResponse) Descriptor() ([]byte, []int) {
	return file_images_service_proto_rawDescGZIP(), []int{18}
}

var File_images_service_proto protoreflect.FileDescriptor

var file_images_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x2e, 0x76, 0x32, 0x22, 0xc8, 0x01, 0x0a, 0x12, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xb1, 0x01, 0x0a, 0x09,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01,
	0x12, 0x16, 0x0a, 0x12, 0x42, 0x41, 0x44, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x46, 0x4f, 0x52,
	0x4d, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f,
	0x49, 0x4d, 0x41, 0x47, 0x45, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x42, 0x41, 0x44, 0x5f, 0x49,
	0x4d, 0x41, 0x47, 0x45, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f, 0x49,
	0x4d, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x4f, 0x4f, 0x5f, 0x4c, 0x41, 0x52, 0x47, 0x45, 0x10, 0x05,
	0x12, 0x14, 0x0a, 0x10, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x42, 0x4c, 0x4f, 0x42,
	0x5f, 0x4b, 0x45, 0x59, 0x10, 0x06, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53,
	0x5f, 0x44, 0x45, 0x4e, 0x49, 0x45, 0x44, 0x10, 0x07, 0x12, 0x14, 0x0a, 0x10, 0x4f, 0x42, 0x4a,
	0x45, 0x43, 0x54, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x08, 0x22,
	0x80, 0x01, 0x0a, 0x16, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x66, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x53, 0x49, 0x5a, 0x45, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x52, 0x4f, 0x54, 0x41, 0x54, 0x45, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x48, 0x4f,
	0x52, 0x49, 0x5a, 0x4f, 0x4e, 0x54, 0x41, 0x4c, 0x5f, 0x46, 0x4c, 0x49, 0x50, 0x10, 0x03, 0x12,
	0x11, 0x0a, 0x0d, 0x56, 0x45, 0x52, 0x54, 0x49, 0x43, 0x41, 0x4c, 0x5f, 0x46, 0x4c, 0x49, 0x50,
	0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x52, 0x4f, 0x50, 0x10, 0x05, 0x12, 0x14, 0x0a, 0x10,
	0x49, 0x4d, 0x5f, 0x46, 0x45, 0x45, 0x4c, 0x49, 0x4e, 0x47, 0x5f, 0x4c, 0x55, 0x43, 0x4b, 0x59,
	0x10, 0x06, 0x22, 0x8c, 0x04, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d,
	0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x25,
	0x0a, 0x0b, 0x63, 0x72, 0x6f, 0x70, 0x5f, 0x74, 0x6f, 0x5f, 0x66, 0x69, 0x74, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x08, 0x3a, 0x05, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x52, 0x09, 0x63, 0x72, 0x6f, 0x70,
	0x54, 0x6f, 0x46, 0x69, 0x74, 0x12, 0x27, 0x0a, 0x0d, 0x63, 0x72, 0x6f, 0x70, 0x5f, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x5f, 0x78, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x02, 0x3a, 0x03, 0x30, 0x2e,
	0x35, 0x52, 0x0b, 0x63, 0x72, 0x6f, 0x70, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x58, 0x12, 0x27,
	0x0a, 0x0d, 0x63, 0x72, 0x6f, 0x70, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x5f, 0x79, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x02, 0x3a, 0x03, 0x30, 0x2e, 0x35, 0x52, 0x0b, 0x63, 0x72, 0x6f, 0x70,
	0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x59, 0x12, 0x19, 0x0a, 0x06, 0x72, 0x6f, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x3a, 0x01, 0x30, 0x52, 0x06, 0x72, 0x6f, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x2e, 0x0a, 0x0f, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x6f, 0x6e, 0x74, 0x61, 0x6c,
	0x5f, 0x66, 0x6c, 0x69, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x3a, 0x05, 0x66, 0x61, 0x6c,
	0x73, 0x65, 0x52, 0x0e, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x6f, 0x6e, 0x74, 0x61, 0x6c, 0x46, 0x6c,
	0x69, 0x70, 0x12, 0x2a, 0x0a, 0x0d, 0x76, 0x65, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x66,
	0x6c, 0x69, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x3a, 0x05, 0x66, 0x61, 0x6c, 0x73, 0x65,
	0x52, 0x0c, 0x76, 0x65, 0x72, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x46, 0x6c, 0x69, 0x70, 0x12, 0x21,
	0x0a, 0x0b, 0x63, 0x72, 0x6f, 0x70, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x5f, 0x78, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x02, 0x3a, 0x01, 0x30, 0x52, 0x09, 0x63, 0x72, 0x6f, 0x70, 0x4c, 0x65, 0x66, 0x74,
	0x58, 0x12, 0x1f, 0x0a, 0x0a, 0x63, 0x72, 0x6f, 0x70, 0x5f, 0x74, 0x6f, 0x70, 0x5f, 0x79, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x02, 0x3a, 0x01, 0x30, 0x52, 0x08, 0x63, 0x72, 0x6f, 0x70, 0x54, 0x6f,
	0x70, 0x59, 0x12, 0x23, 0x0a, 0x0c, 0x63, 0x72, 0x6f, 0x70, 0x5f, 0x72, 0x69, 0x67, 0x68, 0x74,
	0x5f, 0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x3a, 0x01, 0x31, 0x52, 0x0a, 0x63, 0x72, 0x6f,
	0x70, 0x52, 0x69, 0x67, 0x68, 0x74, 0x58, 0x12, 0x25, 0x0a, 0x0d, 0x63, 0x72, 0x6f, 0x70, 0x5f,
	0x62, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x5f, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x3a, 0x01,
	0x31, 0x52, 0x0b, 0x63, 0x72, 0x6f, 0x70, 0x42, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x59, 0x12, 0x25,
	0x0a, 0x0a, 0x61, 0x75, 0x74, 0x6f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x08, 0x3a, 0x05, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x6f, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x73, 0x12, 0x2a, 0x0a, 0x0d, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x73,
	0x74, 0x72, 0x65, 0x74, 0x63, 0x68, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x3a, 0x05, 0x66, 0x61,
	0x6c, 0x73, 0x65, 0x52, 0x0c, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x53, 0x74, 0x72, 0x65, 0x74, 0x63,
	0x68, 0x22, 0x72, 0x0a, 0x09, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x42,
	0x02, 0x08, 0x01, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x62, 0x6c, 0x6f, 0x62, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x62, 0x6c, 0x6f, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a,
	0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0xdd, 0x02, 0x0a, 0x0d, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x88, 0x01, 0x0a, 0x18, 0x63, 0x6f, 0x72, 0x72,
	0x65, 0x63, 0x74, 0x5f, 0x65, 0x78, 0x69, 0x66, 0x5f, 0x6f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x37, 0x2e, 0x61, 0x70, 0x70,
	0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x4f, 0x52, 0x49, 0x45, 0x4e, 0x54, 0x41, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x43, 0x4f, 0x52, 0x52, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x3a, 0x15, 0x55, 0x4e, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x44, 0x5f, 0x4f,
	0x52, 0x49, 0x45, 0x4e, 0x54, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x52, 0x16, 0x63, 0x6f, 0x72, 0x72,
	0x65, 0x63, 0x74, 0x45, 0x78, 0x69, 0x66, 0x4f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x0e, 0x70, 0x61, 0x72, 0x73, 0x65, 0x5f, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x3a, 0x05, 0x66, 0x61, 0x6c, 0x73,
	0x65, 0x52, 0x0d, 0x70, 0x61, 0x72, 0x73, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x40, 0x0a, 0x1c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f,
	0x73, 0x75, 0x62, 0x73, 0x74, 0x69, 0x74, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x67, 0x62,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x1a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x73, 0x74, 0x69, 0x74, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x67, 0x62, 0x22, 0x51, 0x0a, 0x1b, 0x4f, 0x52, 0x49, 0x45, 0x4e, 0x54, 0x41, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x43, 0x4f, 0x52, 0x52, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x12, 0x19, 0x0a, 0x15, 0x55, 0x4e, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x44, 0x5f, 0x4f,
	0x52, 0x49, 0x45, 0x4e, 0x54, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13,
	0x43, 0x4f, 0x52, 0x52, 0x45, 0x43, 0x54, 0x5f, 0x4f, 0x52, 0x49, 0x45, 0x4e, 0x54, 0x41, 0x54,
	0x49, 0x4f, 0x4e, 0x10, 0x01, 0x22, 0x9e, 0x01, 0x0a, 0x0e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x48, 0x0a, 0x09, 0x6d, 0x69, 0x6d, 0x65,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x61, 0x70,
	0x70, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x4d, 0x49, 0x4d, 0x45, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x3a, 0x03, 0x50, 0x4e, 0x47, 0x52, 0x08, 0x6d, 0x69, 0x6d, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x22, 0x28, 0x0a, 0x09,
	0x4d, 0x49, 0x4d, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x4e, 0x47,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x50, 0x45, 0x47, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04,
	0x57, 0x45, 0x42, 0x50, 0x10, 0x02, 0x22, 0xe7, 0x01, 0x0a, 0x16, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2d, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x76, 0x32, 0x2e,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x12, 0x35, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e,
	0x76, 0x32, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x09, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x34, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x67,
	0x69, 0x6e, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x31, 0x0a,
	0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61,
	0x70, 0x70, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x22, 0x71, 0x0a, 0x17, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x6f, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x70,
	0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x22, 0xce, 0x02, 0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x21, 0x0a,
	0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x19, 0x0a, 0x08, 0x78, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x05, 0x52, 0x07, 0x78, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x79,
	0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x02, 0x28, 0x05, 0x52, 0x07, 0x79,
	0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x61, 0x63, 0x69, 0x74,
	0x79, 0x18, 0x04, 0x20, 0x02, 0x28, 0x02, 0x52, 0x07, 0x6f, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79,
	0x12, 0x42, 0x0a, 0x06, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x02, 0x28, 0x0e,
	0x32, 0x2a, 0x2e, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x76, 0x32, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x41, 0x4e, 0x43, 0x48, 0x4f, 0x52, 0x52, 0x06, 0x61, 0x6e,
	0x63, 0x68, 0x6f, 0x72, 0x22, 0x7e, 0x0a, 0x06, 0x41, 0x4e, 0x43, 0x48, 0x4f, 0x52, 0x12, 0x0c,
	0x0a, 0x08, 0x54, 0x4f, 0x50, 0x5f, 0x4c, 0x45, 0x46, 0x54, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03,
	0x54, 0x4f, 0x50, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x4f, 0x50, 0x5f, 0x52, 0x49, 0x47,
	0x48, 0x54, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x45, 0x46, 0x54, 0x10, 0x03, 0x12, 0x0a,
	0x0a, 0x06, 0x43, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x49,
	0x47, 0x48, 0x54, 0x10, 0x05, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x4f, 0x54, 0x54, 0x4f, 0x4d, 0x5f,
	0x4c, 0x45, 0x46, 0x54, 0x10, 0x06, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x4f, 0x54, 0x54, 0x4f, 0x4d,
	0x10, 0x07, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x4f, 0x54, 0x54, 0x4f, 0x4d, 0x5f, 0x52, 0x49, 0x47,
	0x48, 0x54, 0x10, 0x08, 0x22, 0x8c, 0x01, 0x0a, 0x0c, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x43,
	0x61, 0x6e, 0x76, 0x61, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x34, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e,
	0x76, 0x32, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x05, 0x63, 0x6f, 0x6c,
	0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x3a, 0x02, 0x2d, 0x31, 0x52, 0x05, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x22, 0xba, 0x01, 0x0a, 0x16, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x43, 0x6f,
	0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d,
	0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x61, 0x70, 0x70, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a,
	0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x43, 0x6f,
	0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x32, 0x0a, 0x06,
	0x63, 0x61, 0x6e, 0x76, 0x61, 0x73, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61,
	0x70, 0x70, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x73, 0x43, 0x61, 0x6e, 0x76, 0x61, 0x73, 0x52, 0x06, 0x63, 0x61, 0x6e, 0x76, 0x61, 0x73,
	0x22, 0x48, 0x0a, 0x17, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x70,
	0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x47, 0x0a, 0x16, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x73, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e,
	0x76, 0x32, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x22, 0x4d, 0x0a, 0x0f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x65, 0x65,
	0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x67, 0x72, 0x65, 0x65, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x62, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x62, 0x6c,
	0x75, 0x65, 0x22, 0x56, 0x0a, 0x17, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a,
	0x09, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x76, 0x32, 0x2e,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x52,
	0x09, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x22, 0x67, 0x0a, 0x17, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x73, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x62, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x62, 0x4b, 0x65, 0x79,
	0x12, 0x31, 0x0a, 0x11, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x75, 0x72,
	0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x3a, 0x05, 0x66, 0x61, 0x6c,
	0x73, 0x65, 0x52, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x63, 0x75, 0x72, 0x65,
	0x55, 0x72, 0x6c, 0x22, 0x2c, 0x0a, 0x18, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x47, 0x65, 0x74,
	0x55, 0x72, 0x6c, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x22, 0x37, 0x0a, 0x1a, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x55, 0x72, 0x6c, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x62, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x62, 0x4b, 0x65, 0x79, 0x22, 0x1d, 0x0a, 0x1b, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x42, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x61,
	0x70, 0x70, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x76, 0x32, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6d, 0x61, 0x67, 0x65,
}

var (
	file_images_service_proto_rawDescOnce sync.Once
	file_images_service_proto_rawDescData = file_images_service_proto_rawDesc
)

func file_images_service_proto_rawDescGZIP() []byte {
	file_images_service_proto_rawDescOnce.Do(func() {
		file_images_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_images_service_proto_rawDescData)
	})
	return file_images_service_proto_rawDescData
}

var file_images_service_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_images_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_images_service_proto_goTypes = []interface{}{
	(ImagesServiceError_ErrorCode)(0),              // 0: appengine.v2.ImagesServiceError.ErrorCode
	(ImagesServiceTransform_Type)(0),               // 1: appengine.v2.ImagesServiceTransform.Type
	(InputSettings_ORIENTATION_CORRECTION_TYPE)(0), // 2: appengine.v2.InputSettings.ORIENTATION_CORRECTION_TYPE
	(OutputSettings_MIME_TYPE)(0),                  // 3: appengine.v2.OutputSettings.MIME_TYPE
	(CompositeImageOptions_ANCHOR)(0),              // 4: appengine.v2.CompositeImageOptions.ANCHOR
	(*ImagesServiceError)(nil),                     // 5: appengine.v2.ImagesServiceError
	(*ImagesServiceTransform)(nil),                 // 6: appengine.v2.ImagesServiceTransform
	(*Transform)(nil),                              // 7: appengine.v2.Transform
	(*ImageData)(nil),                              // 8: appengine.v2.ImageData
	(*InputSettings)(nil),                          // 9: appengine.v2.InputSettings
	(*OutputSettings)(nil),                         // 10: appengine.v2.OutputSettings
	(*ImagesTransformRequest)(nil),                 // 11: appengine.v2.ImagesTransformRequest
	(*ImagesTransformResponse)(nil),                // 12: appengine.v2.ImagesTransformResponse
	(*CompositeImageOptions)(nil),                  // 13: appengine.v2.CompositeImageOptions
	(*ImagesCanvas)(nil),                           // 14: appengine.v2.ImagesCanvas
	(*ImagesCompositeRequest)(nil),                 // 15: appengine.v2.ImagesCompositeRequest
	(*ImagesCompositeResponse)(nil),                // 16: appengine.v2.ImagesCompositeResponse
	(*ImagesHistogramRequest)(nil),                 // 17: appengine.v2.ImagesHistogramRequest
	(*ImagesHistogram)(nil),                        // 18: appengine.v2.ImagesHistogram
	(*ImagesHistogramResponse)(nil),                // 19: appengine.v2.ImagesHistogramResponse
	(*ImagesGetUrlBaseRequest)(nil),                // 20: appengine.v2.ImagesGetUrlBaseRequest
	(*ImagesGetUrlBaseResponse)(nil),               // 21: appengine.v2.ImagesGetUrlBaseResponse
	(*ImagesDeleteUrlBaseRequest)(nil),             // 22: appengine.v2.ImagesDeleteUrlBaseRequest
	(*ImagesDeleteUrlBaseResponse)(nil),            // 23: appengine.v2.ImagesDeleteUrlBaseResponse
}
var file_images_service_proto_depIdxs = []int32{
	2,  // 0: appengine.v2.InputSettings.correct_exif_orientation:type_name -> appengine.v2.InputSettings.ORIENTATION_CORRECTION_TYPE
	3,  // 1: appengine.v2.OutputSettings.mime_type:type_name -> appengine.v2.OutputSettings.MIME_TYPE
	8,  // 2: appengine.v2.ImagesTransformRequest.image:type_name -> appengine.v2.ImageData
	7,  // 3: appengine.v2.ImagesTransformRequest.transform:type_name -> appengine.v2.Transform
	10, // 4: appengine.v2.ImagesTransformRequest.output:type_name -> appengine.v2.OutputSettings
	9,  // 5: appengine.v2.ImagesTransformRequest.input:type_name -> appengine.v2.InputSettings
	8,  // 6: appengine.v2.ImagesTransformResponse.image:type_name -> appengine.v2.ImageData
	4,  // 7: appengine.v2.CompositeImageOptions.anchor:type_name -> appengine.v2.CompositeImageOptions.ANCHOR
	10, // 8: appengine.v2.ImagesCanvas.output:type_name -> appengine.v2.OutputSettings
	8,  // 9: appengine.v2.ImagesCompositeRequest.image:type_name -> appengine.v2.ImageData
	13, // 10: appengine.v2.ImagesCompositeRequest.options:type_name -> appengine.v2.CompositeImageOptions
	14, // 11: appengine.v2.ImagesCompositeRequest.canvas:type_name -> appengine.v2.ImagesCanvas
	8,  // 12: appengine.v2.ImagesCompositeResponse.image:type_name -> appengine.v2.ImageData
	8,  // 13: appengine.v2.ImagesHistogramRequest.image:type_name -> appengine.v2.ImageData
	18, // 14: appengine.v2.ImagesHistogramResponse.histogram:type_name -> appengine.v2.ImagesHistogram
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_images_service_proto_init() }
func file_images_service_proto_init() {
	if File_images_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_images_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImagesServiceError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_images_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImagesServiceTransform); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_images_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transform); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_images_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_images_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_images_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutputSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_images_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImagesTransformRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_images_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImagesTransformResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_images_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompositeImageOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_images_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImagesCanvas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_images_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImagesCompositeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_images_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImagesCompositeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_images_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImagesHistogramRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_images_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImagesHistogram); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_images_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImagesHistogramResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_images_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImagesGetUrlBaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_images_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImagesGetUrlBaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_images_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImagesDeleteUrlBaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_images_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImagesDeleteUrlBaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_images_service_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_images_service_proto_goTypes,
		DependencyIndexes: file_images_service_proto_depIdxs,
		EnumInfos:         file_images_service_proto_enumTypes,
		MessageInfos:      file_images_service_proto_msgTypes,
	}.Build()
	File_images_service_proto = out.File
	file_images_service_proto_rawDesc = nil
	file_images_service_proto_goTypes = nil
	file_images_service_proto_depIdxs = nil
}
