// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: capability_service.proto

package capability

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsEnabledResponse_SummaryStatus int32

const (
	IsEnabledResponse_DEFAULT          IsEnabledResponse_SummaryStatus = 0
	IsEnabledResponse_ENABLED          IsEnabledResponse_SummaryStatus = 1
	IsEnabledResponse_SCHEDULED_FUTURE IsEnabledResponse_SummaryStatus = 2
	IsEnabledResponse_SCHEDULED_NOW    IsEnabledResponse_SummaryStatus = 3
	IsEnabledResponse_DISABLED         IsEnabledResponse_SummaryStatus = 4
	IsEnabledResponse_UNKNOWN          IsEnabledResponse_SummaryStatus = 5
)

// Enum value maps for IsEnabledResponse_SummaryStatus.
var (
	IsEnabledResponse_SummaryStatus_name = map[int32]string{
		0: "DEFAULT",
		1: "ENABLED",
		2: "SCHEDULED_FUTURE",
		3: "SCHEDULED_NOW",
		4: "DISABLED",
		5: "UNKNOWN",
	}
	IsEnabledResponse_SummaryStatus_value = map[string]int32{
		"DEFAULT":          0,
		"ENABLED":          1,
		"SCHEDULED_FUTURE": 2,
		"SCHEDULED_NOW":    3,
		"DISABLED":         4,
		"UNKNOWN":          5,
	}
)

func (x IsEnabledResponse_SummaryStatus) Enum() *IsEnabledResponse_SummaryStatus {
	p := new(IsEnabledResponse_SummaryStatus)
	*p = x
	return p
}

func (x IsEnabledResponse_SummaryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IsEnabledResponse_SummaryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_capability_service_proto_enumTypes[0].Descriptor()
}

func (IsEnabledResponse_SummaryStatus) Type() protoreflect.EnumType {
	return &file_capability_service_proto_enumTypes[0]
}

func (x IsEnabledResponse_SummaryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *IsEnabledResponse_SummaryStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = IsEnabledResponse_SummaryStatus(num)
	return nil
}

// Deprecated: Use IsEnabledResponse_SummaryStatus.Descriptor instead.
func (IsEnabledResponse_SummaryStatus) EnumDescriptor() ([]byte, []int) {
	return file_capability_service_proto_rawDescGZIP(), []int{1, 0}
}

type IsEnabledRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Package    *string  `protobuf:"bytes,1,req,name=package" json:"package,omitempty"`
	Capability []string `protobuf:"bytes,2,rep,name=capability" json:"capability,omitempty"`
	Call       []string `protobuf:"bytes,3,rep,name=call" json:"call,omitempty"`
}

func (x *IsEnabledRequest) Reset() {
	*x = IsEnabledRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_capability_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsEnabledRequest) ProtoMessage() {}

func (x *IsEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capability_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsEnabledRequest.ProtoReflect.Descriptor instead.
func (*IsEnabledRequest) Descriptor() ([]byte, []int) {
	return file_capability_service_proto_rawDescGZIP(), []int{0}
}

func (x *IsEnabledRequest) GetPackage() string {
	if x != nil && x.Package != nil {
		return *x.Package
	}
	return ""
}

func (x *IsEnabledRequest) GetCapability() []string {
	if x != nil {
		return x.Capability
	}
	return nil
}

func (x *IsEnabledRequest) GetCall() []string {
	if x != nil {
		return x.Call
	}
	return nil
}

type IsEnabledResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SummaryStatus      *IsEnabledResponse_SummaryStatus `protobuf:"varint,1,opt,name=summary_status,json=summaryStatus,enum=appengine.v2.IsEnabledResponse_SummaryStatus" json:"summary_status,omitempty"`
	TimeUntilScheduled *int64                           `protobuf:"varint,2,opt,name=time_until_scheduled,json=timeUntilScheduled" json:"time_until_scheduled,omitempty"`
}

func (x *IsEnabledResponse) Reset() {
	*x = IsEnabledResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_capability_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsEnabledResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsEnabledResponse) ProtoMessage() {}

func (x *IsEnabledResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capability_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsEnabledResponse.ProtoReflect.Descriptor instead.
func (*IsEnabledResponse) Descriptor() ([]byte, []int) {
	return file_capability_service_proto_rawDescGZIP(), []int{1}
}

func (x *IsEnabledResponse) GetSummaryStatus() IsEnabledResponse_SummaryStatus {
	if x != nil && x.SummaryStatus != nil {
		return *x.SummaryStatus
	}
	return IsEnabledResponse_DEFAULT
}

func (x *IsEnabledResponse) GetTimeUntilScheduled() int64 {
	if x != nil && x.TimeUntilScheduled != nil {
		return *x.TimeUntilScheduled
	}
	return 0
}

var File_capability_service_proto protoreflect.FileDescriptor

var file_capability_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70, 0x70, 0x65,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x76, 0x32, 0x22, 0x60, 0x0a, 0x10, 0x49, 0x73, 0x45, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x70,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x70, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x6c, 0x6c, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x63, 0x61, 0x6c, 0x6c, 0x22, 0x8a, 0x02, 0x0a, 0x11, 0x49,
	0x73, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x54, 0x0a, 0x0e, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x61, 0x70, 0x70, 0x65, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x49, 0x73, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0d, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x30, 0x0a, 0x14, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x75,
	0x6e, 0x74, 0x69, 0x6c, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x74, 0x69, 0x6d, 0x65, 0x55, 0x6e, 0x74, 0x69, 0x6c, 0x53,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x22, 0x6d, 0x0a, 0x0d, 0x53, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x46,
	0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x4e, 0x41, 0x42, 0x4c, 0x45,
	0x44, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x43, 0x48, 0x45, 0x44, 0x55, 0x4c, 0x45, 0x44,
	0x5f, 0x46, 0x55, 0x54, 0x55, 0x52, 0x45, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x43, 0x48,
	0x45, 0x44, 0x55, 0x4c, 0x45, 0x44, 0x5f, 0x4e, 0x4f, 0x57, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08,
	0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x05, 0x32, 0x63, 0x0a, 0x11, 0x43, 0x61, 0x70, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x09,
	0x49, 0x73, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x70, 0x65,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x49, 0x73, 0x45, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x70, 0x65,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x49, 0x73, 0x45, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x34, 0x5a, 0x32,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72,
	0x67, 0x2f, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x76, 0x32, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79,
}

var (
	file_capability_service_proto_rawDescOnce sync.Once
	file_capability_service_proto_rawDescData = file_capability_service_proto_rawDesc
)

func file_capability_service_proto_rawDescGZIP() []byte {
	file_capability_service_proto_rawDescOnce.Do(func() {
		file_capability_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_capability_service_proto_rawDescData)
	})
	return file_capability_service_proto_rawDescData
}

var file_capability_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_capability_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_capability_service_proto_goTypes = []interface{}{
	(IsEnabledResponse_SummaryStatus)(0), // 0: appengine.v2.IsEnabledResponse.SummaryStatus
	(*IsEnabledRequest)(nil),             // 1: appengine.v2.IsEnabledRequest
	(*IsEnabledResponse)(nil),            // 2: appengine.v2.IsEnabledResponse
}
var file_capability_service_proto_depIdxs = []int32{
	0, // 0: appengine.v2.IsEnabledResponse.summary_status:type_name -> appengine.v2.IsEnabledResponse.SummaryStatus
	1, // 1: appengine.v2.CapabilityService.IsEnabled:input_type -> appengine.v2.IsEnabledRequest
	2, // 2: appengine.v2.CapabilityService.IsEnabled:output_type -> appengine.v2.IsEnabledResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_capability_service_proto_init() }
func file_capability_service_proto_init() {
	if File_capability_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_capability_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsEnabledRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_capability_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsEnabledResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_capability_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_capability_service_proto_goTypes,
		DependencyIndexes: file_capability_service_proto_depIdxs,
		EnumInfos:         file_capability_service_proto_enumTypes,
		MessageInfos:      file_capability_service_proto_msgTypes,
	}.Build()
	File_capability_service_proto = out.File
	file_capability_service_proto_rawDesc = nil
	file_capability_service_proto_goTypes = nil
	file_capability_service_proto_depIdxs = nil
}
