name: ci

on:
  push:
    branches: [ master, qa ]
  pull_request:
    branches: [ master, qa ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.11.x']
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      env:
        GO111MODULE: on
      run: |
        go get .
        mkdir /tmp/sdk
        curl -o /tmp/sdk.zip "https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.68.zip"
        unzip -q /tmp/sdk.zip -d /tmp/sdk
        # NOTE: Set the following env vars in the test script:
        # export PATH="$PATH:/tmp/sdk/go_appengine"
        # export APPENGINE_DEV_APPSERVER=/tmp/sdk/go_appengine/dev_appserver.py
    - name: Test
      shell: bash
      run: |
        go version
        export PATH="$PATH:/tmp/sdk/go_appengine"
        export APPENGINE_DEV_APPSERVER=/tmp/sdk/go_appengine/dev_appserver.py
        go test -v google.golang.org/appengine/...
        go test -v -race google.golang.org/appengine/...
